### ISSUE TITLE
alpha, scaleX, scaleY tweens do not work.

### ISSUE THREAD

**Issue by scarletsquig** [openfl/actuate#58] opened 2015-05-21 16:55 UTC
Hi, recently did a haxelib upgrade and updated the game I've been working on for the past 6 months to use the new architecture and classes. Went 100% smoothly, with one exception -  Actuate ignoring alpha and scaleX/ scaleY tweens. 

x and y tweens work fine.

Currently using Actuate [1.8.5] and openfl [3.0.6].

Previous build I had where the tweens worked fine was Actuate [1.8.1] and openfl [2.2.4].

Thanks!

EDIT: The same bug occurs even if I compile with the <set name="openfl-legacy" /> tag in place. Doing clean builds in all cases.

**Comment by scarletsquig** [comment] 2015-05-21 18:02
Some additional info:

html5 builds are working correctly.

Values of 0 and 1 for alpha, scaleX and scaleY work correctly, values like 0.5, 0.4 etc. do not and appear to be rounded to 0 or 1.

**Comment by jgranick** [comment] 2015-05-23 01:46
It sounds like something is being cast as an Int on C++ instead of Float. Did you change HXCPP or Haxe versions as well?

**Comment by jgranick** [comment] 2015-05-23 03:22
I just tried a little change in Actuate that might resolve this, please feel free to try it on your install to see if it makes a difference, otherwise, I'd love to know a way to reproduce

**Comment by scarletsquig** [comment] 2015-05-25 10:02
I most likely did change HXCPP/ Haxe versions since I hadn't updated anything in several months then did a straight haxelib upgrade.

Here's my haxelib list, previous working version is listed before the one in brackets:

actuate: 1.7.3 1.7.5 1.8.1 1.8.5 [dev:C:\HaxeToolkit\actuate]
hxcpp: 3.0.2 3.1.39 3.1.68 [3.2.94]
hxlibc: [1.1.4]
lime-tools: 1.2.9 1.3.0 1.4.0 1.5.4 1.5.6 [1.5.7]
lime: 0.9.4 0.9.7 1.0.0 1.0.1 2.0.1 2.0.6 [2.4.1]
openfl-html5: [1.4.2-beta]
openfl-native: 1.2.2 [1.4.0]
openfl-samples: 1.3.0 2.1.0 2.2.1 [2.2.2]
openfl-tools: [1.0.10]
openfl: 1.2.2 1.3.0 1.4.0 2.0.0 2.0.1 2.1.7 2.2.4 [3.0.6]
spritesheet: [1.2.0]
swf: 1.5.2 1.7.0 1.7.6 [1.8.7]
systools: [1.1.0]

Just tried using a development build of actuate (I presume this is the correct way to test your change?) and it hasn't changed anything, non-integer values don't work.

**Comment by ProPuke** [comment] 2015-05-25 15:16
This is a duplicate of #57. I've pointed out the fix.

**Closed** 2015-05-26 15:13 UTC
